project:
  type: website

website:
  title: "Analytics at Scale"

  navbar:
    search: true
    tools:
      - icon: github
        menu:
          - text: Website Source Code
            href: https://github.com/Analyticsphere/analytics-at-scale-workshop
          - text: Analyticshpere
            href: https://github.com/analyticsphere

  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - meeting-notes.qmd
      - section: Tutorials
        contents: tutorials/*.*md
      - section: External Tutorials
        contents: 
          - text: "Count by Period w/ DBI"
            url: https://analyticsphere.github.io/c4cp/articles/count_by_period_vignette.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

