project:
  type: website

execute:
  freeze: auto

website:
  title: "Analytics at Scale"

  navbar:
    search: true
    tools:
      - icon: github
        text: Quarto Website Source Code
        href: https://github.com/Analyticsphere/analytics-at-scale-workshop

  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: scaling_your_r_project.qmd
        text: Scaling Your R Project
      - meeting-notes.qmd
      - section: Tutorials
        contents: tutorials/*.*md
      - section: External Tutorials
        contents:
          - text: "Count by Period w/ DBI"
            url: https://analyticsphere.github.io/c4cp/articles/count_by_period_vignette.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

