on:
  push:
    branches: main

name: Render and Publish

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        # with:
          # r-version: '4.4.1' # Specify if needed

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/R/library
          key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install R Packages
        env:
          R_LIBS_USER: ${{ github.workspace }}/R/library
        run: |
          mkdir -p $R_LIBS_USER
          install.packages(c("knitr", "rmarkdown"), repos = "https://cloud.r-project.org/")

      - name: Verify R Packages Installation
        run: |
          Rscript -e "library(knitr, lib.loc = Sys.getenv('R_LIBS_USER'))"
          Rscript -e "library(rmarkdown, lib.loc = Sys.getenv('R_LIBS_USER'))"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          # version: '1.2.3' # Uncomment to pin Quarto version

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
